// <auto-generated />
namespace SejaHeroi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class rebuild_migrations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rebuild_migrations));
        
        string IMigrationMetadata.Id
        {
            get { return "202110212333455_rebuild_migrations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
